# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: PowerShell@2
  displayName: 'Create date variable'
  inputs:
    targetType: 'inline'
    script: |
      $dateFormatted=$(Get-Date -Format yyyMMdd);
      Write-Host "##vso[task.setvariable variable=date]$dateFormatted"

- task: CmdLine@2
  displayName: 'Copy contents to tmp folder'
  inputs:
    script: '_NO-BN_TransferFilesToTmpFolder.bat'
    workingDirectory: 'NO-BN'


- task: nsis@1
  displayName: 'Create installer'
  inputs:
    scriptFile: 'NO-BN\Installer\NOBN_install.nsi'
    justInclude: 'no'
    includeMorePlugins: 'no'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'Solutions/Installer/BaneNOR.install-$(date).exe'
    artifact: 'NO-BN Installer'
    publishLocation: 'pipeline'

