# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# RailCOMPLETE Azure build pipeline for administration 'XX-YY'
#
# Variables that must be defined to build correct name for installation file etc (example values).
# ACcess / modify by selecting EDIT on a pipeline in Azure DevOps, then add/modify variable.
#
# adm               XX-YY
# buildNumberMajor  2021
# buildNumberMinor  a
#

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: Code-signing-variables

name: $(buildNumberMajor).$(buildNumberMinor)$(Rev:.rrrr)

steps:

- task: PowerShell@2
  displayName: 'Create date variable'
  inputs:
    targetType: 'inline'
    script: |
      $dateFormatted=$(Get-Date -Format yyyMMdd);
      Write-Host "##vso[task.setvariable variable=date]$dateFormatted"

- task: CmdLine@2
  displayName: 'Copy contents to tmp folder'
  inputs:
    script: 'TransferFilesToAzureTmpFolder.bat'
    

- task: nsis@1
  displayName: 'Create installer'
  inputs:
    scriptFile: '$(adm)\Installer\DnaInstallScript.nsi'
    arguments: '/DPRODUCT=RC-$(adm)-$(Build.BuildNumber) /DBUNDLEDIR=$(adm)'
    justInclude: 'no'
    includeMorePlugins: 'no'


- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global azuresigntool'
  displayName: Install AzureSignTool

- task: CmdLine@2
  displayName: 'Sign installer'
  inputs:
    script: 'AzureSignTool sign -du "$(DescriptionURL)" -kvu "$(SigningVaultURL)" -kvi "$(SigningClientId)" -kvs "$(SigningClientSecret)" -kvc "$(CertificateName)" -tr "http://rfc3161timestamp.globalsign.com/advanced" -td "SHA256" -v "$(adm)/Installer/RC-$(adm)-$(Build.BuildNumber).install-$(date).exe"'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(adm)/Installer/RC-$(adm)-$(Build.BuildNumber).install-$(date).exe'

    artifact: '$(adm) Installer'
    publishLocation: 'pipeline'

